services:
  frontend:
    container_name: local-chat_frontend
    build: ./frontend
    ports:
      - "80:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: yarn dev --host

  backend:
    container_name: local-chat_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ./main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-chat
      POSTGRES_HOST: database
    depends_on:
      - database

  database:
    container_name: local-chat_database
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-chat
