services:
  frontend:
    container_name: local-chat_frontend
    build: ./frontend
    ports:
      - "80:5173"
    environment:
      VITE_API_URL: "18.231.42.223:8000"
    depends_on:
      - backend_api
    command: yarn dev --host

  backend_api:
    container_name: local-chat_backend
    build: ./backend
    ports:
      - "8000:8000"
    command: go run ./cmd/main.go
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-chat
      POSTGRES_HOST: database
    depends_on:
      - database

  database:
    container_name: local-chat_database
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-chat
