services:
  simple-chat_frontend:
    container_name: simple-chat_frontend
    build: ./frontend
    ports:
      - "80:5173"
    environment:
      VITE_API_URL: "18.231.42.223:8000"
    depends_on:
      - simple-chat_backend
    command: yarn dev --host
    

  simple-chat_backend:
    container_name: simple-chat_backend
    build: ./backend
    ports:
      - "8000:8000"
    command: go run ./cmd/main.go
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: local-chat
      POSTGRES_HOST: database
    depends_on:
      - database


  database:
    container_name: simple-chat_database
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: local-chat
