name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build containers
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USER@$HOST 'rm -rf ~/simple-chat/docker-compose.override.yml''
          ssh -i private_key.pem $USER@$HOST 'cd ~/simple-chat && sudo docker compose up -d'
          rm -f private_key.pem
