name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Build containers
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            rm -f ~/simple-chat/.env &&
            echo 'POSTGRES_USER=$POSTGRES_USER' >> ~/simple-chat/.env &&
            echo 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD' >> ~/simple-chat/.env &&
            cd ~/simple-chat && git pull && 
            rm -rf ~/simple-chat/docker-compose.override.yml &&
            cd ~/simple-chat && sudo docker compose up -d
          "
          rm -f private_key.pem
